### ISSUE TITLE
cci org info packaging shouldn't give stack trace if no packaging.org file

### ISSUE THREAD

**Issue by boakley** [SFDO-Tooling/CumulusCI#1023]
On a whim I ran `cci org info packaging` in my repo, and got gnarly stack trace rather than a human-friendly  message. The script should not be giving out a stack trace.

Desired output (more-or-less):
```
(cci) bash-3.2 $ cci org info packaging
Org information could not be found. Expected to find encrypted file at /Users/boakley/.cumulusci/Cumulus/packaging.org
```

Actual output:
```
(cci) bash-3.2 $ cci org info packaging
Traceback (most recent call last):
  File "/usr/local/bin/cci", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cci')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/boakley/dev/CumulusCI/cumulusci/cli/cci.py", line 219, in new_func
    func(config, *args, **kw)
  File "/Users/boakley/dev/CumulusCI/cumulusci/cli/cci.py", line 791, in org_info
    org_name, org_config = config.get_org(org_name)
  File "/Users/boakley/dev/CumulusCI/cumulusci/cli/config.py", line 91, in get_org
    org_config = self.keychain.get_org(org_name)
  File "/Users/boakley/dev/CumulusCI/cumulusci/core/keychain/BaseProjectKeychain.py", line 169, in get_org
    self._raise_org_not_found(name)
  File "/Users/boakley/dev/CumulusCI/cumulusci/core/keychain/EncryptedFileProjectKeychain.py", line 102, in _raise_org_not_found
    self.project_local_dir, name
cumulusci.core.exceptions.OrgNotFound: Org information could not be found. Expected to find encrypted file at /Users/boakley/.cumulusci/Cumulus/packaging.org
```

**Comment by davisagli** [comment]
Just to be clear, this happens for `cci org info` with any org name that hasn't been configured; it isn't something special about "packaging"
