### ISSUE TITLE
Show a more helpful error when network access is missing

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#1452]
Example of current behavior:

```
cci version
CumulusCI version: 3.3.0 (/Users/pprescod/.venvs/abacus-py37/bin/cci)
Python version: 3.7.6 (/Users/pprescod/.venvs/abacus-py37/bin/python3)

Traceback (most recent call last):
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x106664a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cumulusci/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106664a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pprescod/.venvs/abacus-py37/bin/cci", line 10, in <module>
    sys.exit(main())
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 247, in version
    latest_version = get_latest_final_version()
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 86, in get_latest_final_version
    res = requests.get("https://pypi.org/pypi/cumulusci/json", timeout=5).json()
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/pprescod/.venvs/abacus-py37/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cumulusci/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106664a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by davisagli** [comment]
We added a better error message in cumulusci 3.6.0
