### ISSUE TITLE
Proposal: Change error handling

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#1494]
I envision the following future user interface:

    $ cci some command
    Error: Xyzzy
    Type `cci error help` for more information about debugging errors.

    $ cci error help

    If you'd like to dig into this error more yourself, you can get the last few lines 
    of context about it from 'cci error info'.

    If you'd like to submit it to a developer for conversation, you can 
    use the 'cci error gist' command. Just make sure that your GitHub access token 
    has the 'create gist' scope.

    For more info see: https://cumulusci.readthedocs.io/en/latest/features.html#reporting-error-logs
    
    $ cci error info
    You can get the FULL TRACE from <path to full history>. Here are the last <x> lines:

    Traceback (most recent call last):
    File "/Users/pprescod/code/CumulusCI/cumulusci/cli/cci.py", line 218, in main
        cli(standalone_mode=False)
    File "/Users/pprescod/.venvs/CCI-37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
    File "/Users/pprescod/.venvs/CCI-37/lib/python3.7/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
    File "/Users/pprescod/.venvs/CCI-37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/Users/pprescod/.venvs/CCI-37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/Users/pprescod/.venvs/CCI-37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
    File "/Users/pprescod/code/CumulusCI/cumulusci/cli/cci.py", line 165, in new_func
        func(RUNTIME, *args, **kw)
    File "/Users/pprescod/code/CumulusCI/cumulusci/cli/cci.py", line 281, in shell
        runpy.run_path(script, init_globals={**globals(), **locals()})
    File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
        pkg_name=pkg_name, script_name=fname)
    File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
    File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File "foo.py", line 11, in <module>
        foo()
    File "foo.py", line 7, in foo
        1 / 0
    ZeroDivisionError: division by zero
    > /Users/pprescod/code/CumulusCI/foo.py(7)foo()
    -> 1 / 0

====

If the log file has the words "Traceback (most recent call last):" in the last 1000 lines, that's where it should start printing. Otherwise I guess it could just print the last 15 lines.

**Comment by prescod** [comment]
If the log file has the words "Traceback (most recent call last):
" in the last 1000 lines, that's where it should start printing. Otherwise I guess it could just print the last 15 lines.
