### ISSUE TITLE
Error when Merges the latest commit on the master branch into all open feature branches 

### ISSUE THREAD

**Issue by pronitagrawalvera** [SFDO-Tooling/CumulusCI#1556]
I am trying to merge the latest commit on the master branch into all open feature branches  but I am getting error  for cci task run github_parent_to_children and  github_master_to_feature

`C:\AutoMerge>cci task run github_parent_to_children
2020-02-19 17:45:04: Beginning task: MergeBranch
2020-02-19 17:45:04:

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\cci.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\cumulusci\cli\cci.py", line 209, in new_func
    func(config, *args, **kw)
  File "c:\python37\lib\site-packages\cumulusci\cli\cci.py", line 1257, in task_run
    handle_exception_debug(config, debug, no_prompt=no_prompt)
  File "c:\python37\lib\site-packages\cumulusci\cli\cci.py", line 1240, in task_run
    task()
  File "c:\python37\lib\site-packages\cumulusci\core\tasks.py", line 140, in __call__
    self.result = self._run_task()
  File "c:\python37\lib\site-packages\cumulusci\tasks\github\merge.py", line 46, in _run_task
    self.repo = self.get_repo()
  File "c:\python37\lib\site-packages\cumulusci\tasks\github\base.py", line 16, in get_repo
    self.project_config.repo_owner, self.project_config.repo_name
  File "c:\python37\lib\site-packages\github3\github.py", line 1981, in repository
    json = self._json(self._get(url), 200)
  File "c:\python37\lib\site-packages\github3\models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found`

`C:\AutoMerge>cci task run github_master_to_feature
2020-02-19 17:57:16: Beginning task: MergeBranch
2020-02-19 17:57:16:

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\cci.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\cumulusci\cli\cci.py", line 209, in new_func
    func(config, *args, **kw)
  File "c:\python37\lib\site-packages\cumulusci\cli\cci.py", line 1257, in task_run
    handle_exception_debug(config, debug, no_prompt=no_prompt)
  File "c:\python37\lib\site-packages\cumulusci\cli\cci.py", line 1240, in task_run
    task()
  File "c:\python37\lib\site-packages\cumulusci\core\tasks.py", line 140, in __call__
    self.result = self._run_task()
  File "c:\python37\lib\site-packages\cumulusci\tasks\github\merge.py", line 46, in _run_task
    self.repo = self.get_repo()
  File "c:\python37\lib\site-packages\cumulusci\tasks\github\base.py", line 16, in get_repo
    self.project_config.repo_owner, self.project_config.repo_name
  File "c:\python37\lib\site-packages\github3\github.py", line 1981, in repository
    json = self._json(self._get(url), 200)
  File "c:\python37\lib\site-packages\github3\models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found`

**Comment by davisagli** [comment]
@pronitagrawalvera Have you configured the CumulusCI github service with a user that has access to this repository? https://cumulusci.readthedocs.io/en/latest/tutorial.html#github-service

**Comment by pronitagrawalvera** [comment]
Hi @davisagli,

Yes, I have configured CumulusCI github service.

Note:I am trying this on my local machine.

![image](https://user-images.githubusercontent.com/58841386/75004367-db549a00-5490-11ea-9f80-4ca0b40fc01c.png)

**Comment by davisagli** [comment]
@pronitagrawalvera hmm. Here are some more things to check:
1. Make sure that the github user you connected has permission to view this repository.
2. If you're using a Personal Access Token rather than a password, make sure the Personal Access Token has the `repo` scope enabled.

**Comment by pronitagrawalvera** [comment]
Hi @davisagli,

My Organization don't have an account on git, we use Bitbucket, Is there a way we can connect to bitbucket repository

**Comment by davisagli** [comment]
Sorry, the parts of CumulusCI that interact with a version control system currently only support GitHub.

**Comment by pronitagrawalvera** [comment]
Hi @davisagli , We thought Bitbucket was supported through CumulusCI. Do you guys have any plans to support this in future, we want to implement this functionality using Cumulusci.

**Comment by jlantz** [comment]
@pronitagrawalvera We don't have any current plans to support Bitbucket as we don't have any internal use cases for it yet.  Our tools are built primarily for the needs of Salesforce.org's managed package products and our community extending and implementing our products.  I can't rule out the possibility of it becoming a priority at some point, but it's not on our current roadmap.

We're open to community contributions that add tasks for other VCS's as long as they have mocked test coverage to help us avoid regressions since we wouldn't have an environment for testing against Bitbucket.  If you're interested in pursuing this route, we'd be happy to answer any questions you run into.

Most of CumulusCI's functionality isn't Github specific.  The exceptions are the tasks that start with github_* and the `update_dependencies` flow if using the `github:` prefix for a dependency. 
 There are a few flows that wire in github specific tasks but individual projects can remove those from their flows via the project's cumulusci.yml file.  For example, the `ci_feature` flow runs that task as step 5 in the flow definition which could be removed with the following in the project's cumulusci.yml:

```
flows:
    ci_feature:
        steps:
            5:
                tasks: None
```

Another option would be to implement custom tasks in your project for any Bitbucket interaction you need.  We have some documentation on creating custom tasks using Python inside your project's repository:
https://cumulusci.readthedocs.io/en/latest/cookbook.html#custom-tasks-via-python

There's an official Bitbucket Python client from Atlassian.  The source for our Github specific tasks are located in the folder linked below.  Since Bitbucket has many of the similar concepts in its API, they might serve as a good reference for how to write similar logic in Bitbucket:
https://github.com/SFDO-Tooling/CumulusCI/tree/master/cumulusci/tasks/github

Here's info on the Bitbucket client module for Python:
https://pypi.org/project/bitbucket-python/
