### ISSUE TITLE
cci org connect Fails with Bad Request

### ISSUE THREAD

**Issue by aesanch2** [SFDO-Tooling/CumulusCI#1592]
Encountered this error when attempting to connect a packaging org for a new project.

OS: MacOS 10.15
```
CumulusCI version: 3.8.0
Python version: 3.7.6 (/usr/local/opt/python/bin/python3.7)
Environment Info: Darwin / x86_64


Last Command Run
================================
/usr/local/bin/cci org connect packaging
Launching web browser for URL https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id=3MVG9JZ_r.QzrS7hROVbLg.VPABtNSJxVSD.gvDHpGO5cw7tmQ1dA3Jnm3eolCARJvVkVAeHjCmZv43UpU9rL&redirect_uri=https://localhost:8080/callback&scope=web%20full%20refresh_token&prompt=login
Spawning HTTP server at https://localhost:8080/callback with timeout of 300 seconds.
If you are unable to log in to Salesforce you can press ctrl+c to kill the server and return to the command line.
127.0.0.1 - - [04/Mar/2020 16:56:23] code 400, message Bad request version ('>\x08\x00"JJ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
127.0.0.1 - - [04/Mar/2020 16:56:23] "üÝ¶ß§ã)í[,Udê8ø¢¿zubÍ®Þ%Ê.4 CÒ	P2Qý÷\K°(ÆövÖË]$yÔ.>"JJÀ+À/À,À0Ì©Ì¨ÀÀ/5" 400 -
Error: 'NoneType' object has no attribute 'status_code'
Type `cci error --help` for more information about debugging errors.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 219, in main
    cli(standalone_mode=False)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 166, in new_func
    func(RUNTIME, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 866, in org_connect
    oauth_dict = oauth_capture()
  File "/usr/local/lib/python3.7/site-packages/cumulusci/oauth/salesforce.py", line 160, in __call__
    self._check_response(self.response)
  File "/usr/local/lib/python3.7/site-packages/cumulusci/oauth/salesforce.py", line 164, in _check_response
    if response.status_code == http.client.OK:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by davisagli** [comment]
Make sure your connected app callback URL is set to http://localhost:8080/callback rather than https://localhost:8080/callback -- CumulusCI is expecting to receive the callback via HTTP, not HTTPS.
