### ISSUE TITLE
Failure during upgrade with Pipx

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/CumulusCI#1773]
**Describe the bug**
While trying to run the pipx upgrade I first got an error saying it was planning to use the wrong version of Faker and then a Type error and stack trace.  After a second run it looks like it completed successfully.

Is there a way to validate the install is actually correct all around?

```
> pipx upgrade cumulusci
ERROR: snowfakery 0.8.1 has requirement Faker>=4.0.3, but you'll have faker 4.0.2 which is incompatible.
```

After awhile Python threw a Type Error:
```
Traceback (most recent call last):
    "__main__", mod_spec)
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
  File "C:\Users\ahcrosman\AppData\Local\Programs\Python\Python37\Scripts\pipx.exe\__main__.py", line 7, in <module>
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\site-packages\pipx\main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\site-packages\pipx\main.py", line 192, in run_pipx_command
    venv_dir, package, pip_args, verbose, upgrading_all=False, force=args.force
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\site-packages\pipx\commands\upgrade.py", line 59, in upgrade
    is_main_package=True,
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\site-packages\pipx\venv.py", line 337, in upgrade_package
    is_main_package=is_main_package,
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\site-packages\pipx\venv.py", line 265, in _update_package_metadata
    venv_package_metadata = self.get_venv_metadata_for_package(package)
  File "c:\users\ahcrosman\appdata\local\programs\python\python37\lib\site-packages\pipx\venv.py", line 254, in get_venv_metadata_for_package
    return VenvMetadata(**data)
TypeError: __new__() missing 1 required positional argument: 'apps_of_dependencies'
```

On a second run it appears to complete successfully:
```
> pipx upgrade cumulusci

  Overwriting file C:\Users\ahcrosman\.local\bin\cci.exe with C:\Users\ahcrosman\.local\pipx\venvs\cumulusci\Scripts\cci.exe
upgraded package cumulusci from 3.12.1 to 3.12.2 (location: C:\Users\ahcrosman\.local\pipx\venvs\cumulusci)
```
And it appears faker was updated to a more recent version (the following was run from within the cci venv):
```
>>> import pkg_resources
>>> pkg_resources.get_distribution("faker").version
'4.1.0'
```

**Context**
- CumulusCI version: 3.12.2 (C:\Users\ahcrosman\.local\bin\cci)
- Python version: 3.7.7 (c:\users\ahcrosman\.local\pipx\venvs\cumulusci\scripts\python.exe)
- Windows 10: Version	10.0.18363 Build 18363
- PowerShell within VSCode

**Comment by davisagli** [comment]
The error looks like a problem with pipx, not cumulusci -- but I think we can help avoid it by explicitly pinning the version of Faker required by cumulusci (which should have been there already, but is not).

Faker 4.1.0 is correct for cumulusci 3.12.2 so I think you're good to go.
