### ISSUE TITLE
New Project Init Generates Malformed YAML

### ISSUE THREAD

**Issue by aesanch2** [SFDO-Tooling/CumulusCI#1780]
**Describe the bug**
When initializing a new project with `cci project init`, the `cumulus.yml` file is not generated correctly. This results in parser errors when running subsequent `cci` commands.

```
❯ cci flow run dev_org --org dev
Traceback (most recent call last):
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/bin/cci", line 11, in <module>
    load_entry_point('cumulusci==3.13.0', 'console_scripts', 'cci')()
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/cli/cci.py", line 202, in main
    RUNTIME = CliRuntime(load_keychain=False)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/cli/runtime.py", line 22, in __init__
    super(CliRuntime, self).__init__(*args, **kwargs)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/core/runtime.py", line 25, in __init__
    self._load_project_config(*args, **kwargs)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/core/runtime.py", line 76, in _load_project_config
    self.global_config, *args, **kwargs
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/core/config/project_config.py", line 65, in __init__
    super(BaseProjectConfig, self).__init__(config=config)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/core/config/BaseConfig.py", line 15, in __init__
    self._load_config()
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/core/config/project_config.py", line 96, in _load_config
    project_config = cci_safe_load(f_config)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/cumulusci/utils/yaml/cumulusci_yml.py", line 40, in cci_safe_load
    rc = yaml.safe_load(StringIO(data))
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/Cellar/cumulusci/3.13.0/libexec/lib/python3.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<file>", line 8, column 9
expected <block end>, but found '<scalar>'
  in "<file>", line 8, column 39
```

A sample of the generated `cumulus.yml` file:
```
minimum_cumulusci_version: '3.13.0'
project:
    name: [--]
    package:
        name:  [--]
        api_version: '47'
    git: 
        default_branch: 'mainline'    test:
        name_match: '%Test'
    source_format: sfdx

tasks:
    robot:
        options:
            suites: robot/[--]/tests
            options:
                outputdir: robot/[--]/results

    robot_testdoc:
        options:
            path: robot/[--]/tests
            output: robot/[--]/doc/[--]_tests.html

    run_tests:
        options:
            required_org_code_coverage_percent: 75
```

Both the `api_version` and `test` entries are not formatted correctly. Fixing these by hand resolves the issues.

**Reproduction steps**
1. Initialize a new project with 3.13.0
2. Specify an API version other than the default
3. Specify a test regex other than the default
4. Run another `cci` command e.g. `cci org info dev`

**Context**
- Your CumulusCI version (`cci version`): 3.13.0
- Your Python version (`python --version`): 3.7.3
- Your operating system and version: macOS 10.15.5
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`: Installed with `brew`

**Comment by davisagli** [comment]
Thanks for the report.

**Comment by umeditor** [comment]
I just ran into this as well. Ended up with an invalid `cumulus.yml` when setting up a new project with `Default Branch` set to `main`.

`cumulusci.yml` generated by `cci project init`:
```
minimum_cumulusci_version: '3.14.0'
project:
    name: cci-test
    package:
        name:  cci-test
        api_version: '48.0'
    git: 
        default_branch: 'main'    source_format: sfdx

tasks:
    robot:
        options:
            suites: robot/cci-test/tests
            options:
                outputdir: robot/cci-test/results

    robot_testdoc:
        options:
            path: robot/cci-test/tests
            output: robot/cci-test/doc/cci-test_tests.html

    run_tests:
        options:
            required_org_code_coverage_percent: 75
```
