### ISSUE TITLE
Can't Install Using linuxbrew

### ISSUE THREAD

**Issue by ranbirdasgit** [SFDO-Tooling/CumulusCI#1781]
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/cumulusci/3.13.0/libexec/bin/cci", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    @_call_aside
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jeepney>=0.4.2' distribution was not found and is required by keyring

**Comment by davisagli** [comment]
@ranbirdasgit sorry, it looks like our homebrew formula is not working with linuxbrew because keyring has additional dependencies on linux which are not included in the formula.

As a workaround, first uninstall the broken homebrew package:
$ brew uninstall cumulusci

And then try installing like this instead:
$ brew install pipx
$ pipx ensurepath
$ pipx install cumulusci

**Comment by davisagli** [comment]
On Linux we currently recommend installing using pipx: https://cumulusci.readthedocs.io/en/stable/get_started.html#on-linux
