### ISSUE TITLE
Error connecting to Github service.

### ISSUE THREAD

**Issue by juan-cs** [SFDO-Tooling/CumulusCI#1968]
**Describe the bug**
When I run `cci service connect github`, I get `Unable to store CumulusCI encryption key. You can configure it manually by setting the CUMULUSCI_KEY environment variable to a random 16-character string. ERROR: Failed to create the collection: Prompt dismissed.`.

I get the same result even if I manually set `CUMULUSCI_KEY` using `export CUMULUSCI_KEY=<16 chars>`.

**Reproduction steps**
1. Run `cci service connect github` on an existing project.

**Context**
Please include the following information at minimum.

- Your CumulusCI version (`cci version`): 3.17.1
- Your Python version (`python --version`): 3.8.5
- Your operating system and version: Windows 10, build 19041.450.
- If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL: WSL2
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`: `pip`.

**Gist**
`cci error gist` shows the error above, but `cci error info` shows:
```
Traceback (most recent call last):
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 221, in main
    cli(standalone_mode=False)
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 777, in get_command
    runtime._load_keychain()
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/cumulusci/core/runtime.py", line 80, in _load_keychain
    keychain_key = self.keychain_key if self.keychain_cls.encrypted else None
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/cumulusci/core/runtime.py", line 61, in keychain_key
    return self.get_keychain_key()
  File "/home/<user>/anaconda3/envs/cumulusci/lib/python3.8/site-packages/cumulusci/cli/runtime.py", line 55, in get_keychain_key
    raise KeychainKeyNotFound(
cumulusci.core.exceptions.KeychainKeyNotFound: Unable to store CumulusCI encryption key. You can configure it manually by setting the CUMULUSCI_KEY environment variable to a random 16-character string. ERROR: Failed to create the collection: Prompt dismissed..
```

**Comment by juan-cs** [comment]
@davidmreed , thanks for the quick response.

> Were you successfully using CumulusCI 3.16 on WSL2 prior to upgrading?
I use an old version on a CI/CD server, but I just installed it locally for the first time in years.

I will try downgrading to 3.16 and it now works as expected after setting the `CUMULUSCI_KEY` variable.

Is there anything I can test to help?

**Comment by davidmreed** [comment]
Thank you for that input - I wanted to establish whether this is a regression in CumulusCI 3.17.1, and it sounds like that is clearly not the case. I don't believe there's any additional testing required. 

I would recommend that for the time being you use CumulusCI in Windows rather than WSL2, where we do officially support it.

**Comment by juan-cs** [comment]
Sorry my comment was not clear. It did work with 3.16. 
Thanks again for the quick responses.
