### ISSUE TITLE
C2 - push upgrade with option subscriber_where sends malformed request

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/CumulusCI#209]
Found when pushing HEDAP release to sandbox orgs.

$ cumulusci2 task run push_all --org packaging -o version 3.87 -o start_time 2016-12-22T02:00 -o subscriber_where "OrgType = 'Sandbox'"
Traceback (most recent call last):
  File "/Users/cpolcyn/dev/CumulusCI/venv/bin/cumulusci2", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cumulusci2')()
...
simple_salesforce.api.SalesforceMalformedRequest: Malformed request https://na30.salesforce.com/services/data/v35.0/query/?q=SELECT+id%2C+name%2C+namespaceprefix+FROM+MetadataPackage+WHERE+NamespacePrefix+%3D+%27hed%27+LIMIT+1. Response content: [{u'errorCode': u'INVALID_TYPE', u'message': u"sObject type 'MetadataPackage' is not supported."}]

**Comment by cpolcyn** [comment]
https://help.salesforce.com/articleView?id=000247523&type=1

**Comment by GulDmitry** [comment]
Faced this while calling `cci flow run release_beta` using docker-compose:
```
version: '3'
services:
  cumulus:
    build: ./docker/cumulusCI
    container_name: sde-cumulus
    ports:
      - 8080:8080
    volumes:
      - /var/www/salesforce-demo/:/root
    command: cci
    environment:
        - CUMULUSCI_KEY=2c5409bbc5ea321b # Must be 16
    network_mode: host
```

DockerFile to build:
```
FROM debian:jessie

RUN apt-get update && apt-get install -y \
    rsync \
    telnet \
    curl \
    wget \
    build-essential \
    libssl-dev \
    libffi-dev \
    python-dev

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN apt-get install -y python-pip

RUN pip install cryptography
# TypeError: data must be a byte string.
RUN pip install 'requests[security]'

RUN pip install http
RUN pip install --upgrade ndg-httpsclient

RUN pip install --pre cumulusci

WORKDIR /root
```

A new org can be successfully connected:
`docker-compose run cumulus cci project init`
`docker-compose run cumulus cci org config_connected_app`
`docker-compose run -p 8080:8080 cumulus cci org connect prod`

Commands like `docker-compose run cumulus cci flow run ci_feature` works fine on empty `package.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>Test Package</fullName>
    <version>40.0</version>
</Package>
```

But this causes the error:
`cci flow run ci_master` - makes a valid package.
`cci flow run release_beta`

Log:
```

+ cci flow run ci_master
...
2017-06-26 21:37:12: Retrieving metadata using /usr/local/lib/python2.7/dist-packages/cumulusci/files/admin_profile.xml
2017-06-26 21:37:12: Pending
2017-06-26 21:37:15: [Done]
2017-06-26 21:37:17: Processing retrieved metadata in /tmp/tmpyv0wVY
2017-06-26 21:37:17: Deploying updated Admin.profile from /tmp/tmpyv0wVY
2017-06-26 21:37:17: Pending
2017-06-26 21:37:20: [InProgress]: Processing Type: CustomObject
2017-06-26 21:37:23: [Done]
2017-06-26 21:37:24: [Success]: Succeeded
2017-06-26 21:37:24: Task complete: update_admin_profile
+ cci flow run release_beta
2017-06-26 21:37:25: ---------------------------------------
2017-06-26 21:37:25: Initializing flow class BaseFlow:
2017-06-26 21:37:25: ---------------------------------------
2017-06-26 21:37:25: Flow Description: Uploads and releases a beta version of the metadata currently in packaging
2017-06-26 21:37:25: Tasks:
2017-06-26 21:37:25:   upload_beta: Uploads a beta release of the metadata currently in the packaging org
2017-06-26 21:37:25:   github_release: Creates a Github release for a given managed package version number
2017-06-26 21:37:25:   github_release_notes: Generates release notes by parsing pull request bodies of merged pull requests between two tags
2017-06-26 21:37:25:   github_master_to_feature: Merges the latest commit on the master branch into all open feature branches
2017-06-26 21:37:25: Organization:
2017-06-26 21:37:25:   Username: demo-production@dgulyakevich.com
2017-06-26 21:37:25:     Org Id: 00D7F000000pvCXUAY
2017-06-26 21:37:25: 
2017-06-26 21:37:25: Running task: upload_beta
2017-06-26 21:37:27: Options:
2017-06-26 21:37:27:   name: Automated beta release
2017-06-26 21:37:27:   namespace: demonamespace
2017-06-26 21:37:27: Beginning task: PackageUpload
2017-06-26 21:37:27: 
2017-06-26 21:37:29: Task failed: upload_beta
2017-06-26 21:37:29: Failing flow due to exception in task
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cumulusci/core/flows.py", line 171, in _run_task

    task()

  File "/usr/local/lib/python2.7/dist-packages/cumulusci/core/tasks.py", line 95, in __call__

    self.result = self._run_task()

  File "/usr/local/lib/python2.7/dist-packages/cumulusci/tasks/salesforce.py", line 1121, in _run_task

    package_res = sf.query("select Id from MetadataPackage where NamespacePrefix='{}'".format(self.options['namespace']))

  File "/usr/local/lib/python2.7/dist-packages/simple_salesforce/api.py", line 334, in query

    result = self._call_salesforce('GET', url, params=params, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/simple_salesforce/api.py", line 433, in _call_salesforce

    _exception_handler(result)

  File "/usr/local/lib/python2.7/dist-packages/simple_salesforce/api.py", line 792, in _exception_handler

    raise exc_cls(result.url, result.status_code, name, response_content)

SalesforceMalformedRequest: Malformed request https://ap5.salesforce.com/services/data/v38.0/query/?q=select+Id+from+MetadataPackage+where+NamespacePrefix%3D%27demonamespace%27. Response content: [{u'errorCode': u'INVALID_TYPE', u'message': u"sObject type 'MetadataPackage' is not supported."}]

Traceback (most recent call last):

  File "/usr/local/bin/cci", line 11, in <module>

    sys.exit(cli())

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func

    return ctx.invoke(f, obj, *args[1:], **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/cumulusci/cli/cli.py", line 760, in flow_run

    flow()

  File "/usr/local/lib/python2.7/dist-packages/cumulusci/core/flows.py", line 109, in __call__

    self._run_task(flow_task_config)

  File "/usr/local/lib/python2.7/dist-packages/cumulusci/core/flows.py", line 180, in _run_task

    raise e

simple_salesforce.api.SalesforceMalformedRequest: Malformed request https://ap5.salesforce.com/services/data/v38.0/query/?q=select+Id+from+MetadataPackage+where+NamespacePrefix%3D%27demonamespace%27. Response content: [{u'errorCode': u'INVALID_TYPE', u'message': u"sObject type 'MetadataPackage' is not supported."}]
```

**Comment by cpolcyn** [comment]
Hi @GulDmitry that looks like a potentially different issue since it doesn't deal with querying orgs for push upgrade. Please file a new issue for your comment here.

**Comment by cpolcyn** [comment]
Hi @GulDmitry do you have Packaging Push API enabled as shown in the link in my [comment](https://github.com/SalesforceFoundation/CumulusCI/issues/209#issuecomment-287866917) above? We are able to run the release_beta flow without problem.
