### ISSUE TITLE
Custom tasks fail in MacOS due to _posixsubprocess being undefined

### ISSUE THREAD

**Issue by edmondo1984** [SFDO-Tooling/CumulusCI#2183]
**Describe the bug**
It looks that one cannot run custom tasks in MacOS neither with python 3.7.3 nor 3.8.1 due to some akward behaviour affecting _posixsubmodules. I am running MACOS Catalina 10.15.4

When running a custom task, cumulus fails when trying to update credentials:

`
Traceback (most recent call last):
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 225, in main
    cli(standalone_mode=False)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 1514, in run_task
    task()
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/tasks.py", line 133, in __call__
    self._update_credentials()
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/tasks.py", line 255, in _update_credentials
    self.org_config.refresh_oauth_token(self.project_config.keychain)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/config/SfdxOrgConfig.py", line 152, in refresh_oauth_token
    self._load_orginfo()
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/config/OrgConfig.py", line 177, in _load_orginfo
    self._org_sobject = self.salesforce_client.Organization.get(self.org_id)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/config/OrgConfig.py", line 123, in salesforce_client
    session_id=self.access_token,
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/config/SfdxOrgConfig.py", line 79, in access_token
    return self.sfdx_info["access_token"]
TypeError: 'NoneType' object is not subscriptable

`

As I dug down what is happening on that line, I found out the problem is in SfdxOrgConfig.py here: https://github.com/SFDO-Tooling/CumulusCI/blob/master/cumulusci/core/config/SfdxOrgConfig.py#L31

as this command is not returning the result. I have wrapped that lines into an exception handler and enabled check_return=True :

`
        try: 
            p = sfdx("force:org:display --json", self.username, check_return=True)
        except Exception as e:
            import traceback
            traceback.print_exc()    
`

and now the failure is the following

```

Traceback (most recent call last):
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/config/SfdxOrgConfig.py", line 37, in sfdx_info
    p = sfdx("force:org:display --json", self.username, check_return=True)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/cumulusci/core/sfdx.py", line 47, in sfdx
    p.run()
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-1-qe3xrZyf-py3.8/lib/python3.8/site-packages/sarge/__init__.py", line 667, in run
    self.process = p = Popen(self.args, **self.kwargs)
  File "/Users/edmondoporcu1/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/edmondoporcu1/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
AttributeError: 'NoneType' object has no attribute 'fork_exec'

```

The interesting thing is that, given an AttributeError is being returned, the @property annotation swallows it. I think there are two issues here:

- We should probably throw a custom exception when the `sfdx` command fail to get a meaningful error returned to the user
- It looks like sarge is overrwriting some posix primitives, because importing _posixsubprocess in a plain python terminal works

```
Python 3.8.1 (default, Jul  8 2020, 22:01:40) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _posixsubprocess
>>> print(_posixsubprocess)
<module '_posixsubprocess' from '/Users/edmondoporcu1/.pyenv/versions/3.8.1/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-darwin.so'>
>>> exit()
 ```

**Comment by davisagli** [comment]
CumulusCI is generally working on macOS (it's what we use for developing it), so I would guess that this is something wrong with the Python you are using, or possibly a bad interaction with some other package installed in the virtualenv.

Have you installed any other Python packages along with cumulusci? I searched for this error (`AttributeError: 'NoneType' object has no attribute 'fork_exec'`) and see some discussions that mention the `gevent` library. CumulusCI does not depend on gevent so it would not be normal to have it installed. But, I don't know for sure if it is gevent; there could be some other library that triggers the same problem.

**Comment by edmondo1984** [comment]
@davisagli what I have found, after investigaiton, is that there is no problem with CumulusCI, except that I was trying to write a custom task to consume platform events and assess they were correctly emitted in a roboframework test.

Guess what, the python_bayeux from the salesforce foundation perform a mocking of gevent at line 

https://github.com/SalesforceFoundation/python-bayeux/blob/master/src/python_bayeux/__init__.py#L32

and this replace the _posixsupbrocess module.

It was not a problem with cumulusCI, but still how to test platform event emission is an open question. Can we reach out to @adamlincoln , who is a mantainer of python-bayeux ? It's a project from Salesforce foundation too

**Comment by davisagli** [comment]
@edmondo1984 We can ask Adam, but he is in a different role than when python-bayeux was created and I doubt it is actively maintained.

Also I doubt that it is a problem with python-bayeux per se; more likely the problem is simply that the gevent monkey patches are getting installed too late. This is a common problem when using gevent; its patches need to be installed as the very first thing when the process starts, or else we end up in a situation where some modules are using the patched code and some are not.

You could try adding the gevent initialization to the __init__.py for the cumulusci package to make sure it is loaded early. If this helps, I would probably be okay with adding this to CumulusCI inside a conditional import so that it doesn't cause problems when gevent is not installed.

However I will caution that since gevent monkey patches a lot of core Python libraries to make them non-blocking, and since we are not actively testing with it, we can't commit to providing support if using gevent causes some other part of CumulusCI to behave differently.

If I were to start implementing a Python client for the streaming API today, I would be interested in doing it using asyncio rather than gevent. https://pypi.org/project/aiocometd/ looks like it could be worth a look.

**Comment by edmondo1984** [comment]
@davisagli very interesting thanks. I'll think about it, I guess being able to assert that the right platform event was emitted or that a notification occurs on a push topic is particularly useful given there is no apex support for testing these scenarios.

What about my proposal to wrap, in any case, the sfdx command into an exception handler that will rethrow failures into a custom exception so to avoid the problem with the property annotation?

**Comment by davisagli** [comment]
@edmondo1984 Properties swallowing AttributeError is a recurring frustration in Python. I like the idea of guarding against that in some way. Using a wrapper that catches AttributeError and raises something else is one option, and may be the best way to do this that preserves backwards compatibility. (If this were new code, I'd suggest that sfdx_info should be accessed as a method rather than a property, to avoid this problem and make it more obvious that it can potentially do significant work.)

One possibility would be a generic safe_property decorator:

def safe_property(func):
    def new_func(*args, **kw):
        try:
            return func(*args, **kw)
        except AttributeError as err:
            raise SomeOtherError(f"Property function raised {err}")
    return property(new_func)

and then sfdx_info could be defined like this:

    @safe_property
    def sfdx_info(self):
        # same as existing implementation

**Comment by edmondo1984** [comment]
Happy to submit a PR in that direction if you prefer having that decorator, I had in mind to wrap the execution of the sfdx command not the property itself, literally this method here

https://github.com/SFDO-Tooling/CumulusCI/blob/3fe45c4ae22eb4d42447d9118ee38745b4151caf/cumulusci/core/sfdx.py#L47

**Comment by davisagli** [comment]
@edmondo1984 I'd prefer that decorator because:
- I don't see a reason to transform AttributeError into something else when sfdx is being called from a different context that's not accessed as a property.
- The sfdx_info property does other things along with calling sfdx, so there is potential for an AttributeError to come from somewhere else too.

**Comment by adamlincoln** [comment]
Hi @edmondo1984 , @davisagli , I think the 1.0.0 release of python-bayeux will help.  See https://github.com/SalesforceFoundation/python-bayeux/issues/10 .
