### ISSUE TITLE
UTF Decode Error on Windows in SFDX exception handling

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2250]
A user generated this gist which indicated bugs in our decoding/exception handling:

```
CumulusCI version: 3.25.0
Python version: 3.8.2 (c:\users\username\.local\pipx\venvs\cumulusci\scripts\python.exe)
Environment Info: Windows / AMD64


Last Command Run
================================
C:\Users\username\Documents\SFRepositories\omega>cci org scratch release OmegaMain --default --days 7
OmegaMain is now the default org

C:\Users\username\Documents\SFRepositories\omega>cci flow run regression_org
2020-12-14 11:54:27: ============================================================
2020-12-14 11:54:27: Initializing flow: FlowCoordinator (regression_org)
2020-12-14 11:54:27: Simulates an org that has been upgraded from the latest relea
se of to the current beta and its dependencies, but deploys any unmanaged metadata from the current beta.
2020-12-14 11:54:27: ============================================================ 
2020-12-14 11:54:27:
2020-12-14 11:54:27: Verifying and refreshing credentials for the specified org: O
megaMain.
2020-12-14 11:54:27: Creating scratch org with command: sfdx force:org:create -f o
rgs/release.json -n --durationdays 7 -a "Omega__OmegaMain" -s -w 120 adminEmail="username@salesforce.com"

Error: Failed to create scratch org: 

WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring 
’21 release, the feature isn't automatically enabled. You must manually enable the setting 
for new scratch orgs. Enable the setting in one of these ways: update the Account Settings 
page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.
ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from "sfdx force:data:record:get -s ScratchOrgInfo -i 2SR4p000000QYb9GAG -u username@sfdo.devhub".
Run this command for more information about debugging errors: cci error --help
Traceback (most recent call last):
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 229, in main
    cli(args[1:], standalone_mode=False)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 172, in new_func
    func(RUNTIME, *args, **kw)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 1769, in flow_run
    coordinator.run(org_config)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\flowrunner.py", line 394, in run
    self._init_org()
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\flowrunner.py", line 667, in _init_org
    self.org_config.refresh_oauth_token(self.project_config.keychain)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\config\sfdx_org_config.py", line 211, in refresh_oauth_token
    self.sfdx_info
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\config\sfdx_org_config.py", line 23, in sfdx_info
    self.create_org()
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\config\ScratchOrgConfig.py", line 101, in create_org
    raise ScratchOrgException(message)
cumulusci.core.exceptions.ScratchOrgException: Failed to create scratch org:

WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring 
’21 release, the feature isn't automatically enabled. You must manually enable the setting 
for new scratch orgs. Enable the setting in one of these ways: update the Account Settings 
page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.
ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from "sfdx force:data:record:get -s ScratchOrgInfo -i 2SR4p000000QYb9GAG -u username@sfdo.devhub".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\utils\logging.py", line 34, in tee_stdout_stderr
    yield
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 240, in main
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\.local\bin\cci.exe\__main__.py", line 7, in <module>
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 240, in main
    sys.exit(1)
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\username\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\utils\logging.py", line 45, in tee_stdout_stderr
    contents = f.read()
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 3310: invalid start byte

C:\Users\username\Documents\SFRepositories\omega>cci error gist
Gist created: https://gist.github.com/3506d485423bc652b8edad001c5a6444
```

**Comment by prescod** [comment]
@Br4nd0R 

I think that the following patch may fix the problem:

```
diff --git a/cumulusci/utils/logging.py b/cumulusci/utils/logging.py
index bfff40db..b584f624 100644
--- a/cumulusci/utils/logging.py
+++ b/cumulusci/utils/logging.py
@@ -41,8 +41,9 @@ def tee_stdout_stderr(args, logger, tempfile):
         logger.handlers[0].close()
 
         # log contents of tempfile to rotating log files
-        with open(tempfile, "r", encoding="utf-8") as f:
-            contents = f.read()
+        with open(tempfile, "rb") as f:
+            binary_data = f.read()
+            contents = binary_data.decode("utf-8", errors='backslashreplace')
 
         logger = get_gist_logger()
         logger.debug(contents)
```

**Comment by davisagli** [comment]
I think we want to figure out why the tempfile is getting written with the wrong encoding rather than just replacing characters

**Comment by avisser** [comment]
My team is running to this same issue when loading a dataset. We applied the fix @prescod to tasks\bulkdata\load.py in `_sqlite_load` and worked around the issue. However, our Windows users are running into this.

Please address!

**Comment by prescod** [comment]
@avisser Thank you for tellling us about your challenge. The issue should be fixed in the version of CumulusCI that is released tomorrow.

**Comment by prescod** [comment]
@avisser : David Glick pointed out that the issue your user is having is similar but seems not identical. We fixed logging.py but you had a similar issue in _sqlite_load. It's quite concerning that there are characters in the sql file that cannot be loaded on Windows. Do you have any insight into what the characters are which are causing the problem, and how they got into the file? Did you edit the file in a text editor or is it what the extract task created?
