### ISSUE TITLE
Cannot complete task "github_release" as part of any release flows

### ISSUE THREAD

**Issue by sbutterfield** [SFDO-Tooling/CumulusCI#2324]
https://github.com/SFDO-Tooling/CumulusCI/blob/44b0d6a3e44427652f018e23684e37d232e7eaf0/cumulusci/tasks/github/release.py#L50

full stacktrace:
  ~/dev_local/cumulusci_trailhead/resilient-hawk-oybvk2   master release_candidate  cci error info                                    1 ↵  1012  14:58:40

Traceback (most recent call last):
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 229, in main
    cli(args[1:], standalone_mode=False)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 172, in new_func
    func(RUNTIME, *args, **kw)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 1769, in flow_run
    coordinator.run(org_config)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/core/flowrunner.py", line 416, in run
    self._run_step(step)
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/core/flowrunner.py", line 455, in _run_step
    raise result.exception  # PY3: raise an exception type we control *from* this exception instead?
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/core/flowrunner.py", line 250, in run_step
    task()
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/core/tasks.py", line 141, in __call__
    self.result = self._run_task()
  File "/usr/local/Cellar/cumulusci/3.26.0/libexec/lib/python3.8/site-packages/cumulusci/tasks/github/release.py", line 50, in _run_task
    release = repo.release_from_tag(tag_name)
AttributeError: 'NoneType' object has no attribute 'release_from_tag'

**Comment by sbutterfield** [comment]
I haven't taken steps to break point debug this. It's likely something is wrong in my config, I just cannot pinpoint what it is. I've tried uninstalling and reinstalling cci numerous times, even reverting to previous versions (3.22->3.25 have all been tried). I have used brew and pipx to manage the cumulusci install - no change. I've also disconnected and reconnected cci to github using two different tokens - no luck.

I'm just playing around with a test project, but this seems to be systemic with other new projects as well. 

Here's my cumulusci.yml: 
minimum_cumulusci_version: '3.22.0'
project:
    name: resilient-hawk-oybvk2
    package:
        name: <redacted>
        api_version: '50.0'
        namespace: <redacted>
        version: Winter21
    git:
        default_branch: main
        repo_url: <redacted>
    source_format: sfdx

tasks:
    robot:
        options:
            suites: robot/resilient-hawk-oybvk2/tests
            options:
                outputdir: robot/resilient-hawk-oybvk2/results

    robot_testdoc:
        options:
            path: robot/resilient-hawk-oybvk2/tests
            output: robot/resilient-hawk-oybvk2/doc/resilient-hawk-oybvk2_tests.html

flows:
    config_qa:
        steps:
            3:
                task: load_dataset
    config_dev:
        steps:
            3:
                task: load_dataset

**Comment by davisagli** [comment]
@sbutterfield The error indicates that CumulusCI is getting `None` where it's expecting to have an object for interacting with the GitHub API for repositories. Some things to check:

1. CumulusCI looks up the GitHub repo owner and name from the `origin` git remote. Check that this is finding the expected values by running `cci shell --python "print(project_config.repo_owner, project_config.repo_name)"`
2. Make sure that you've configured CumulusCI's github service (`cci service connect github`) using a Personal Access Token which includes the `repo` scope, for a user that has access to this repository.

**Comment by sbutterfield** [comment]
@davisagli, `cci shell --python "print(project_config.repo_owner, project_config.repo_name)"` << really useful command, thank you!

Totally PEBKAC issue - my project name, repo name, and package name were all misaligned. The lightbulb really clicked when I received a more descriptive error that the project wasn't connected to github (despite connecting it multiple times). 🤦🏻

**Comment by sbutterfield** [comment]
Closing this issue - I have a follow-up that I'll file separately @davisagli

**Comment by lordgordon** [comment]
Had the same problem. I fixed changing my git config repository's url from SSH to HTTPS.

Are SSH repos supported?

**Comment by davisagli** [comment]
@lordgordon ssh repo URLs should work, but it's possible there's a bug in the code that's parsing the url to find the repository owner and name. If you'd like us to take a look, please open a new issue and share the ssh url that didn't work (replacing pieces of it with fake values if you don't want to reveal the actual url)
