### ISSUE TITLE
Cannot generate Data Dictionary

### ISSUE THREAD

**Issue by mishraankit191** [SFDO-Tooling/CumulusCI#2604]
**If you are seeking support on using CumulusCI, please do not open an Issue. Instead, please visit us on the [Trailblazer Community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009M9Z), or, for Nonprofit and Education customers, the [Power of Us Hub](https://powerofus.force.com/s/group/0F980000000PSRHCA4/cumulusci-cci)**

**Describe the bug**
Getting error 'NoneType' object is not callable on cci task run generate_data_dictionary

**Reproduction steps**
1. cci task run data dictionary

**Context**
Please include the following information at minimum.

- Your CumulusCI version (`cci version`). CumulusCI version: 3.34.1 (C:\Python38\Scripts\cci)
- Your Python version (`python --version`) Python version: 3.8.5 (c:\python38\python.exe)
- Your operating system and version. Windows 10 Pro 20H2 19042.964
- If using Windows, whether you are using Command Prompt, PowerShell, Bash on Windows, or WSL. Command Prompt
- If possible, whether you installed CumulusCI using `brew`, `pip`, or `pipx`. pip

**Gist**
If applicable, please use the `cci error gist` command to create a Gist from your error log and include the link here. See the [documentation](https://cumulusci.readthedocs.io/en/latest/features.html#working-with-errors) to learn how to create a Gist.
https://gist.github.com/mishraankit191/c05e1b5d4ee9b0121da4a16278c2f496
**Additional information**

**Comment by davidmreed** [comment]
This is a regression in CumulusCI subsequent to version 3.33. I will add it to an upcoming sprint to fix. Thank you for your report!

**Comment by mishraankit191** [comment]
Thank you!

**Comment by mishraankit191** [comment]
dropping gist here and deleting in my user 
CumulusCI version: 3.34.1
Python version: 3.8.5 (c:\python38\python.exe)
Environment Info: Windows / AMD64


Last Command Run
================================
C:\Python38\Scripts\cci task run generate_data_dictionary
2021-05-07 07:52:29: Beginning task: GenerateDataDictionary
2021-05-07 07:52:29: 
2021-05-07 07:52:29: Starting data dictionary generation
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\cumulusci\cli\cci.py", line 78, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Ankit Mishra\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\cumulusci\cli\task.py", line 178, in run_task
    task()
  File "c:\python38\lib\site-packages\cumulusci\core\tasks.py", line 149, in __call__
    self.result = self._run_task()
  File "c:\python38\lib\site-packages\cumulusci\tasks\datadictionary.py", line 186, in _run_task
    repos += self._get_repo_dependencies(dependencies, include_beta=False)
  File "c:\python38\lib\site-packages\cumulusci\tasks\datadictionary.py", line 124, in _get_repo_dependencies
    _, ref = self.project_config.get_ref_for_dependency(
TypeError: 'NoneType' object is not callable

**Comment by davisagli** [comment]
This was fixed in cumulusci 3.37.0
