### ISSUE TITLE
[pyinstaller] executable built on Mac does not run on different Mac

### ISSUE THREAD

**Issue by cpolcyn** [SFDO-Tooling/CumulusCI#290]
Executables of cci built with pyinstaller will fail on other systems (built on Mac, run on another Mac). My hunch is that I was building using Apple's built-in python which was not built with `--enable-shared`. The solution is to build our own with `--enable-shared` and use that to create the virtualenv so that it is bundled in the pyinstaller build.

**Comment by cpolcyn** [comment]
How to tell if python is built with --enable-shared:

```
>>> import sysconfig
>>> sysconfig.get_config_vars('Py_ENABLE_SHARED')
```

**Comment by cpolcyn** [comment]
Not sure how to build python with SSL support on Mac. Follow these steps to reproduce.

Start in Python2.7.13 source dir and configure:
```
$ ./configure --enable-shared
```

Build:
```
$ make
...
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _ssl               dl              
imageop            linuxaudiodev      ossaudiodev     
readline           spwd               sunaudiodev     
```

Some of these we maybe don't need. Like the audio stuff. So let's continue.

Install:
`$ make altinstall # install to /usr/local/bin/python2.7 and /usr/local/lib/python2.7`

Verify shared and SSL:
```
$ /usr/local/bin/python2.7
...
>>> import sysconfig
>>> sysconfig.get_config_vars('Py_ENABLE_SHARED')
[1]
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
```

Create virtual environment:
```
$ virtualenv -p /usr/local/bin/python2.7 venv
Running virtualenv with interpreter /usr/local/bin/python2.7
New python executable in /Users/cpolcyn/Desktop/venv/bin/python2.7
Also creating executable in /Users/cpolcyn/Desktop/venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/cpolcyn/Desktop/venv/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "/Library/Python/2.7/site-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2332, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/cpolcyn/Desktop/venv/bin/python2.7 - setuptools pip wheel failed with error code 1
```

Fails I assume because no SSL support.

**Comment by cpolcyn** [comment]
Here is the original symptom as seen on a Mac running the executable built from another Mac. This was built in one-folder mode with debug enabled.
```
$ ./cci version
PyInstaller Bootloader 3.x
LOADER: executable is /Users/jlantz/Downloads/cci/cci
LOADER: homepath is /Users/jlantz/Downloads/cci
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /Users/jlantz/Downloads/cci/cci
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /Users/jlantz/Downloads/cci
PyInstaller Bootloader 3.x
LOADER: executable is /Users/jlantz/Downloads/cci/cci
LOADER: homepath is /Users/jlantz/Downloads/cci
LOADER: _MEIPASS2 is /Users/jlantz/Downloads/cci
LOADER: archivename is /Users/jlantz/Downloads/cci/cci
LOADER: Already in the child - running user's code.
LOADER: Python library: /Users/jlantz/Downloads/cci/.Python
Error loading Python lib '/Users/jlantz/Downloads/cci/.Python': dlopen(/Users/jlantz/Downloads/cci/.Python, 10): no suitable image found. Did find:
/Users/jlantz/Downloads/cci/.Python: code signature invalid for '/Users/jlantz/Downloads/cci/.Python'
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /Users/jlantz/Downloads/cci/cci
```

**Comment by cpolcyn** [comment]
Not sure yet how this affects Windows and Linux builds.

**Comment by cpolcyn** [comment]
Python installations from both Homebrew and PyEnv are built without `--enable-shared`.

**Comment by davisagli** [comment]
We may try again, but we are not currently supporting PyInstaller.
