### ISSUE TITLE
cci service connect github fails with no error

### ISSUE THREAD

**Issue by ajanicko** [SFDO-Tooling/CumulusCI#2903]
### Describe the bug

Running `cci service connect github github.com` fails without giving any error message.

Traceback (most recent call last):
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 76, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\service.py", line 166, in callback
    updated_conf: dict = validator(serv_conf)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\github.py", line 115, in validate_service
    _ = repo_generator.next()
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\github3\structs.py", line 148, in next
    return self.__next__()
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\github3\structs.py", line 134, in __next__
    return next(self.__i__)
StopIteration

### Reproduction steps

1. Create github account.
2. Create access token
3. Run `cci service connect github github.com`
4. Fill credentials.
5. Hit enter.
6. Look at blank error message.

### Your CumulusCI and Python versions

CumulusCI version: 3.45.0 (C:\Users\ajani\.local\bin\cci)
Python version: 3.9.0 (C:\Users\ajani\.local\pipx\venvs\cumulusci\Scripts\python.exe)

You have the latest version of CumulusCI.

### Operating System

WIndows 10

### Windows environment

PowerShell

### CumulusCI installation method

pipx

**Comment by ajanicko** [comment]
I managed to get a little more info, but I still can't figure out the issue :(
C:\Users\ajani\.local\bin\cci service connect github github.com --debug
2021-10-05 11:46:25,428 DEBUG Added a stderr logging handler to logger: urllib3
2021-10-05 11:46:39,417 DEBUG Starting new HTTPS connection (1): api.github.com:443
2021-10-05 11:46:39,641 DEBUG https://api.github.com:443 "GET /user HTTP/1.1" 200 None
2021-10-05 11:46:39,791 DEBUG https://api.github.com:443 "GET /user/orgs?per_page=100 HTTP/1.1" 200 2
2021-10-05 11:46:39,961 DEBUG https://api.github.com:443 "GET /user/repos?per_page=100 HTTP/1.1" 200 2
Traceback (most recent call last):
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 76, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\service.py", line 166, in callback
    updated_conf: dict = validator(serv_conf)
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\github.py", line 115, in validate_service
    _ = repo_generator.next()
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\github3\structs.py", line 148, in next
    return self.__next__()
  File "C:\Users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\github3\structs.py", line 134, in __next__
    return next(self.__i__)
StopIteration
> c:\users\ajani\.local\pipx\venvs\cumulusci\lib\site-packages\github3\structs.py(134)__next__()
-> return next(self.__i__)
