### ISSUE TITLE
Open Test Browser TypeError: 'NoneType' object is not callable when using useralias param

### ISSUE THREAD

**Issue by ZephyrusMB** [SFDO-Tooling/CumulusCI#3047]
### Describe the bug

Hi,
Trying to open a test browser with a different user of a persistent org gives me this error **TypeError: 'NoneType' object is not callable**. If I use a scratch org the keyword works perfectly and it allows me to open 2 browsers with different accounts. To authenticate i use  'sfdx auth:web:login' for both the persistents accounts, while for the scratch org ones  i generated a password and then created a new profile with sfdx following this [youtube video](https://www.youtube.com/watch?v=sqKb7QbyNJ0).
Here the robot file i execute
```
`*** Settings ***

Resource        cumulusci/robotframework/Salesforce.robot 
Library         cumulusci.robotframework.PageObjects 

Test Teardown    Delete Records and Close Browser
*** Test Cases ***
Utente admin
    Open Test Browser       useralias=Chatter  
Utente UTest
    Open Test Browser            useralias=UTest`

```
Here the log with the same error in each case 
![image](https://user-images.githubusercontent.com/81178328/151055720-562d2a0b-a839-45e7-ab75-00d37187fff2.png)

### Reproduction steps

1.connect to a persistent org with `sfdx auth:web:login` with the first account
2.connect to a persistent org with `sfdx auth:web:login` with the second account
3.execute the file robot with `cci task run robot  --suites pathToFile.robot`
4.get the TypeError: 'NoneType' object is not callable

### Your CumulusCI and Python versions

CumulusCI version: 3.51.0 (C:\Users\${user}\.local\bin\cci)
Python version: 3.9.8 (C:\Users\${users}\.local\pipx\venvs\cumulusci\Scripts\python.exe)

### Operating System

Microsoft Windows 10.0.19042

### Windows environment

Command Prompt

### CumulusCI installation method

pipx

**Comment by davisagli** [comment]
The `useralias` for the `Open Test Browser` keyword refers to an org in the CumulusCI keychain, not the sfdx keychain. In other words the alias needs to show up in `cci org list` in order for it to work. For a persistent org, that means you would need to connect the org using `cci org connect` rather than using sfdx. Unfortunately we don't currently provide a way to import a persistent org from sfdx into the cci keychain.

**Comment by davisagli** [comment]
@ZephyrusMB I'm saying that it will not work unless the persistent orgs have been connected that way. But perhaps there is another problem as well. Could you run `cci error gist` after the NoneType error occurs and provide the link to the gist so that we can see more information about where the error is happening?

**Comment by ZephyrusMB** [comment]
Here it is, I edited some paths or email for privacy reasons.
```
CumulusCI version: 3.51.1
Python version: 3.9.8 
Environment Info: Windows / AMD64

Last Command Run
================================
cci task run robot --suites .\robot\demo\tests\PersistentOrg\PersistentOrgAdmin\openBrowser.robot --robot_debug true
[01/26/22 17:46:31] Org info updated, writing to keychain                                                           
                    Beginning task: Robot                                                                           
                    As user: account@mine.com                                                                          
                    In org: IDORG                                                                      
                                                                                                                    
==============================================================================
openBrowser                                                                   
==============================================================================
Utente Chatter                                                        F.
                                                                              
Utente Chatter                                                        | FAIL |
TypeError: 'NoneType' object is not callable
------------------------------------------------------------------------------
Utente Standard                                                       F.
                                                                              
Utente Standard                                                       | FAIL |
TypeError: 'NoneType' object is not callable
------------------------------------------------------------------------------
openBrowser                                                           | FAIL |
2 tests, 0 passed, 2 failed
==============================================================================
Output:  C:\Users\Desktop\RobotFramework\Cumulusci\PyconDemo\robot\demo\results\output.xml
Log:     C:\Users\Desktop\RobotFramework\Cumulusci\PyconDemo\robot\demo\results\log.html
Report:  C:\Users\Desktop\RobotFramework\Cumulusci\PyconDemo\robot\demo\results\report.html
Error: 2 tests failed.
Run this command for more information about debugging errors: cci error --help
Traceback (most recent call last):
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 79, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\task.py", line 181, in run_task
    task()
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\tasks.py", line 160, in __call__
    self.result = self._run_task()
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\tasks\robotframework\robotframework.py", line 282, in _run_task
    raise RobotTestFailure(
cumulusci.core.exceptions.RobotTestFailure: 2 tests failed.
```

**Comment by davisagli** [comment]
@ZephyrusMB Thanks. Unfortunately since the error happened in a Robot Framework test, the stack trace does not give enough information (it's showing where Robot Framework was called, not where the test failed while Robot Framework was running).

If you look at the Robot Framework log (the log.html file mentioned in the output), does it show any more information about where the error happened?

**Comment by ZephyrusMB** [comment]
I believe you should be able to repeat this error following the steps:

1. log in to a persistent org with the first user with `cci org connect`
2. log in to the same persistent org with the second user with `cci org connect`
3. check the successful connection with `cci org list`
4. run the script in the first post with `cci task run robot --suites path/to/file.robot`

Repeating the test with Setting log level to DEBUG i receive this more info. Thank you  

```
Traceback (most recent call last):
  File "C:\Users\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\robotframework\CumulusCI.py", line 120, in login_url
    access_token = org.get_access_token(**userfields)
```
![Immagine 2022-01-27 091755](https://user-images.githubusercontent.com/81178328/151319190-41cf30ae-6513-4420-831a-719ca4e6492f.png)

**Comment by davisagli** [comment]
@ZephyrusMB Thanks. That traceback makes me realize that unfortunately this is currently implemented in a way that will only work for scratch orgs. Thanks for reporting it.

**Comment by davisagli** [comment]
@davidmreed Can you comment on the likelihood of this being added to our roadmap?

**Comment by davidmreed** [comment]
Tracking as W-10502445

**Comment by jstvz** [comment]
Closing as part of a backlog triage pass against v4.10.0 / 5.0.0.dev1.

Reason: pre-v4.0.0

If this is still reproducible against v4.10.0 (the current latest stable) or against v5.0.0.devN on the dev branch, please reopen with a fresh `cci version` block and reproduction steps. We track v5 development on the `dev` branch.
