### ISSUE TITLE
Cannot release an unlocked beta package with release_unlocked_beta flow

### ISSUE THREAD

**Issue by tahina-netizen** [SFDO-Tooling/CumulusCI#3347]
### Describe the bug

I was trying to release an unlocked beta package of a salesforce app to deploy on a sandbox.
For that, I used `cci flow run release_unlocked_beta`.
However, that flow failed while running his first step: `create_package_version` task.
  
Please see below the command line logs:
```

                    ------------------------------------------------------------
                    Running task: create_package_version
                    ------------------------------------------------------------

                    Options:
                      package_name: Fiaussi
                      package_type: Unlocked
                      version_base: latest_github_release
                      version_type: minor
                      skip_validation: False
                      force_upload: True
                      create_unlocked_dependency_packages: False
                    Org info updated, writing to keychain
                    Getting org info from Salesforce CLI for DevHub
[08/22/22 09:59:54] Beginning task: CreatePackageVersion

                    Checking for existing Unlocked Package named Fiaussi
                    Found 0Ho1v000000XZGKCA4
                    Converting from SFDX to MDAPI format.
[08/22/22 09:59:59] Cleaning meta.xml files of packageVersion elements for deploy
[08/22/22 10:00:00] Exception in task create_package_version

Error: expected str, bytes or os.PathLike object, not NoneType
```

and the python error stack trace:
```
WARNING: Long path support is not enabled. This can lead to errors with some
tasks. Your administrator will need to activate the "Enable Win32 long paths"
group policy, or set LongPathsEnabled to 1 in the registry key
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem.


Traceback (most recent call last):
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\cci.py", line 91, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\runtime.py", line 183, in new_func
    func(runtime, *args, **kw)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\cli\flow.py", line 168, in flow_run
    coordinator.run(org_config)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\flowrunner.py", line 441, in run
    self._run_step(step)
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\flowrunner.py", line 482, in _run_step
    raise result.exception  # PY3: raise an exception type we control *from* this exception instead?
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\flowrunner.py", line 248, in run_step
    task()
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\tasks.py", line 158, in __call__
    self.result = self._run_task()
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\tasks\create_package_version.py", line 221, in _run_task
    self.request_id = self._create_version_request(
  File "C:\Users\zotah\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\tasks\create_package_version.py", line 377, in _create_version_request
    with open(self.org_config.config_file, "r") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Reproduction steps

1. Move to the directory of a salesforce app
2. Run in a _git bash_  command line (on windows): `cci flow run release_unlocked_beta`

### Your CumulusCI and Python versions

CumulusCI version: `3.64.0`
Python version: `3.9.0`

### Operating System

Microsoft Windows 10 Pro, 10.0.19044 Build 19044

### Windows environment

Bash on Windows

### CumulusCI installation method

pipx

### Error Gist

https://gist.github.com/tahina-netizen/0be0d1e0cce07e5adb6f131ef02cba68

### Additional information

My tamporary workaround solution was to directly use `sfdx` to create the unlocked beta package and manually create tag and release in the project remote repository.

**Comment by jstvz** [comment]
Closing as part of a backlog triage pass against v4.10.0 / 5.0.0.dev1.

Reason: stale > 24 months

If this is still reproducible against v4.10.0 (the current latest stable) or against v5.0.0.devN on the dev branch, please reopen with a fresh `cci version` block and reproduction steps. We track v5 development on the `dev` branch.
