### ISSUE TITLE
cci org list stopped to work after running `cci task  run connected_app`

### ISSUE THREAD

**Issue by sauloefo** [SFDO-Tooling/CumulusCI#3425]
### Describe the bug

After run the command:

``` shell
cci task run connected_app --label CciCliForCiCd --connect true --email abc-abc+ab-abcdefg@salesforce.com
```

The following error started to happen on the execution of `cci org list`:

``` shell
[11/03/22 14:54:29] Unable to store an encryption key. Any orgs or services written to disk will not be encrypted.
Error: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Run this command for more information about debugging errors: cci error --help
``` 

### Reproduction steps

1. run `cci task run connected_app --label CciCliForCiCd --connect true --email abc-abc+ab-abcdefg@salesforce.com`

### Your CumulusCI and Python versions

CumulusCI version: 3.68.1 (/home/saulo/.local/bin/cci)
Python version: 3.8.10 (/home/saulo/.local/pipx/venvs/cumulusci/bin/python)

### Operating System

Ubuntu 20.04.5 LTS (Focal Fossa)

### Windows environment

WSL

### CumulusCI installation method

pipx

### Error Gist

cci error gist is causing the same error

### Additional information

Traceback (most recent call last):
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/cli/cci.py", line 91, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/cli/runtime.py", line 182, in new_func
    runtime._load_keychain()
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/core/runtime.py", line 94, in _load_keychain
    self.keychain = self.keychain_cls(self.universal_config, keychain_key)
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/core/keychain/base_project_keychain.py", line 44, in __init__
    self._load_keychain()
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/core/keychain/base_project_keychain.py", line 50, in _load_keychain
    self._load_services()
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/core/keychain/encrypted_file_project_keychain.py", line 575, in _load_services
    self._load_service_files()
  File "/home/saulo/.local/pipx/venvs/cumulusci/lib/python3.8/site-packages/cumulusci/core/keychain/encrypted_file_project_keychain.py", line 695, in _load_service_files
    config = f.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by sauloefo** [comment]
I solved the issue by deleting the connected_app service file: `~/.cumulusci/services/connected_app/CciCliForCiCd.service`
