### ISSUE TITLE
Error when port 8080 for OAuth is not available 

### ISSUE THREAD

**Issue by rwina36** [SFDO-Tooling/CumulusCI#366]
I get this issue when i follow the install guide.

![image](https://user-images.githubusercontent.com/29462587/27692376-d4addb52-5ce6-11e7-982c-d5e82bded5b2.png)
````
(cumulusci_venv) MBP-de-RBE: CumulusCI-Test rbe$ cci org connect dev
Launching web browser for URL https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id=XXXXXXXXX&redirect_uri=http://localhost:8080/callback&scope=web%20full%20refresh_token&prompt=login
Traceback (most recent call last):
  File "/Users/RBE/cumulusci_venv/bin/cci", line 11, in <module>
    load_entry_point('cumulusci==2.0.0b48', 'console_scripts', 'cci')()
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 416, in org_connect
    oauth_dict = oauth_capture()
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/cumulusci/oauth/salesforce.py", line 112, in __call__
    self._create_httpd()
  File "/Users/RBE/cumulusci_venv/lib/python2.7/site-packages/cumulusci/oauth/salesforce.py", line 133, in _create_httpd
    self.httpd = HTTPServer(server_address, OAuthCallbackHandler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use


```

**Comment by jlantz** [comment]
It looks like you have a local Jetty server running on localhost:8080 which is the callback url used by default for CumulusCI to capture OAuth credentials to an org.  If you shut down the Jetty server and then connect the org you should be able to start the Jetty server back up once the org is connected.  The localhost webserver is only used when running `cci org connect`.

I'm leaving this open because we should figure out a better way to handle different callback urls.
