### ISSUE TITLE
Failing deploy task on latest cci build used on circleci: ParseError: mismatched tag: line 3, column 22

### ISSUE THREAD

**Issue by Szandor72** [SFDO-Tooling/CumulusCI#536]
Please see stack trace below: 

```
2018-01-11 17:32:31: Running task: deploy
2018-01-11 17:32:32: Org info updated, writing to keychain
2018-01-11 17:32:32: Options:
2018-01-11 17:32:32:   path: src
2018-01-11 17:32:32: Beginning task: Deploy
2018-01-11 17:32:32: 
2018-01-11 17:32:33: Cleaning meta.xml files of packageVersion elements for deploy
2018-01-11 17:32:33: Task failed: deploy
2018-01-11 17:32:33: Failing flow due to exception in task
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/flows.py", line 191, in _run_task
    task()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/tasks.py", line 113, in __call__
    self.result = self._run_task()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 74, in _run_task
    api = self._get_api()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 355, in _get_api
    zipf = self._process_zip_file(zipf)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 365, in _process_zip_file
    zipf = self._process_meta_xml(zipf)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/tasks/salesforce.py", line 403, in _process_meta_xml
    zipf = zip_clean_metaxml(zipf, logger=self.logger)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/utils.py", line 263, in zip_clean_metaxml
    zip_src.read(name),
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/utils.py", line 83, in remove_xml_element_string
    tree = ET.fromstring(content)
  File "/opt/circleci/python/2.7.12/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/opt/circleci/python/2.7.12/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/opt/circleci/python/2.7.12/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 3, column 22
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.12/bin/cci", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 230, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 1091, in flow_run
    handle_exception_debug(config, debug, e, no_prompt=no_prompt)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 1067, in flow_run
    flow()
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/flows.py", line 129, in __call__
    self._run_task(flow_task_config)
  File "/home/ubuntu/virtualenvs/venv-2.7.12/lib/python2.7/site-packages/cumulusci/core/flows.py", line 200, in _run_task
    raise e
xml.etree.ElementTree.ParseError: mismatched tag: line 3, column 22
```

**Comment by cdcarter** [comment]
likely also related to #530 and #536

**Comment by Szandor72** [comment]
Although #530 only hit me on a win machine? 

For now I reverted back to beta 76 and all is good.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8RAAW" target="_blank">W-022285</a>

**Comment by davisagli** [comment]
I think we did some fixes related to this.
