### ISSUE TITLE
found character '%' that cannot start any token

### ISSUE THREAD

**Issue by mchang-r7** [SFDO-Tooling/CumulusCI#538]
When trying to connect to GitHub using `cci service connect github`, the following error and stack trace is printed.

```txt
Traceback (most recent call last):
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/bin/cci", line 7, in <module>
    from cumulusci.cli.cli import cli
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 241, in <module>
    CLI_CONFIG = CliConfig()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 176, in __init__
    self._load_project_config()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/cli/cli.py", line 192, in _load_project_config
    self.project_config = self.global_config.get_project_config()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/core/config.py", line 762, in get_project_config
    return self.project_config_class(self)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/core/config.py", line 1136, in __init__
    super(YamlProjectConfig, self).__init__(*args, **kwargs)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/core/config.py", line 147, in __init__
    super(BaseProjectConfig, self).__init__(config=config)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/core/config.py", line 57, in __init__
    self._load_config()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/cumulusci/core/config.py", line 1171, in _load_config
    project_config = yaml.load(f_config)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/martyc/Documents/GitHub/mchang-r7/cumulusci/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '%' that cannot start any token
  in "/Users/martyc/Documents/GitHub/martyychang/sf-trigger-workflow/cumulusci.yml", line 6, column 21
```

### Steps to reproduce

1. Open Terminal
2. Activate the `cumulusci` virtual environment
3. `cd` to the local repository
4. `cci project init` and enter "%Test" _without_ the quotes when prompted to enter the SOQL pattern to find test classes
5. `cci service connect github`

### Analysis

The problem seemed to be simply that the YAML config file was created writing "%Test" without actually enclosing the string value in quotes. Python 2 reading the YAML file does not seem to like `%` as the first character coming after `:` to define a value.

**Comment by mchang-r7** [comment]
`cci version` tells me **2.0.0-beta80**

**Comment by cdcarter** [comment]
@mchang-r7 - thanks for reporting the issue. the YAML format requires the value to be quoted if it starts with a %, but we can handle the error better.

**Comment by jlantz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000009KL8QAAW" target="_blank">W-022284</a>
