### ISSUE TITLE
Tests fail when environment variables contain Unicode

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#692]
```bash
export APT_EMOJI=🤬
echo $APT_EMOJI
nosetests
```

Results in several failures, e.g. `test_unset_default_org`:

```python
Traceback (most recent call last):
  File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/tests/test_keychain.py", line 231, in test_unset_default_org
    self._test_unset_default_org()
  File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/tests/test_keychain.py", line 234, in _test_unset_default_org
    keychain = self.keychain_class(self.project_config, self.key)
  File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/keychain/BaseProjectKeychain.py", line 24, in __init__
    self._load_keychain()
  File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/keychain/BaseProjectKeychain.py", line 51, in _load_keychain
    self._load_orgs()
  File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/keychain/EnvironmentProjectKeychain.py", line 35, in _load_orgs
    for key, value in self._get_env():
  File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/keychain/EnvironmentProjectKeychain.py", line 22, in _get_env
    return [(k.decode(), v.decode()) for k,v in list(os.environ.items())]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
```

Commands execute without throwing an exception, however.

**Comment by cdcarter** [comment]
its like we just started throwing decode() calls everywhere, hoping that they'd fix things...

**Comment by davisagli** [comment]
Python 3 takes care of decoding `os.environ` -- I'm not sure if it uses Python's sys.getdefaultencoding() or tries to determine the encoding that the system is using for environment variables, which is probably ideal. So I think we need to decode only in Python 2, and be smarter about which encoding to use.

**Comment by jstvz** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fNVrAAM" target="_blank">W-028232</a>

**Comment by jstvz** [comment]
Resolved by the move to py3

**Comment by jstvz** [comment]
**lurch: close
