### ISSUE TITLE
Better error when service connect is called with an undefined service name

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#752]
Current behavior:
```
$ cci service connect foo
Checking the version!
An update to CumulusCI is available. Use pip install --upgrade cumulusci to update.
Traceback (most recent call last):
  File "/Users/dglick/.pyenv/versions/cci-dev-py27/bin/cci", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cci')()
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/dglick/Work/CumulusCI/cumulusci/cli/cci.py", line 574, in get_command
    config.project_config, "services__{0}__attributes".format(name)
AttributeError: 'NoneType' object has no attribute 'items'
```

**lurch: add

**Comment by davisagli** [comment]
@ceiroa I think what we want to do in this situation is raise ServiceNotValid (from cumulusci.core.exceptions) with a more helpful message.
