### ISSUE TITLE
CCI fails on Ubuntu 18.04.

### ISSUE THREAD

**Issue by FabriRamos** [SFDO-Tooling/CumulusCI#781]
This is the  traceback i get after following the tutorial:
`$ cci version

Traceback (most recent call last):
  File "/home/fabrizio/.pyenv/versions/cci/bin/cci", line 11, in <module>
    sys.exit(main())
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/cumulusci/cli/cci.py", line 189, in main
    check_latest_version()
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/cumulusci/cli/cci.py", line 98, in check_latest_version
    latest_version = get_latest_version()
  File "/home/fabrizio/.pyenv/versions/2.7.14/envs/cci/lib/python2.7/site-packages/cumulusci/cli/cci.py", line 83, in get_latest_version
    cache["cumulusci-latest-timestamp"] = str(time.time())
  File "/home/fabrizio/.pyenv/versions/2.7.14/lib/python2.7/dumbdbm.py", line 163, in __setitem__
    raise TypeError, "keys and values must be strings"
TypeError: keys and values must be strings`

Let me know if further details are needed about my enviroment.
Thanks

**Comment by davisagli** [comment]
Thanks for the report. A fix for this issue will be included in the next release of cumulusci.
