### ISSUE TITLE
Bulk data load breaks in Python 2

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#827]
```
Traceback (most recent call last):
  File "/Users/dglick/.pyenv/versions/cci-dev-py27/bin/cci", line 11, in <module>
    load_entry_point('cumulusci', 'console_scripts', 'cci')()
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/dglick/Work/CumulusCI/cumulusci/cli/cci.py", line 212, in new_func
    func(config, *args, **kw)
  File "/Users/dglick/Work/CumulusCI/cumulusci/cli/cci.py", line 1027, in task_run
    handle_exception_debug(config, debug, no_prompt=no_prompt)
  File "/Users/dglick/Work/CumulusCI/cumulusci/cli/cci.py", line 1010, in task_run
    task()
  File "/Users/dglick/Work/CumulusCI/cumulusci/core/tasks.py", line 132, in __call__
    self.result = self._run_task()
  File "/Users/dglick/Work/CumulusCI/cumulusci/tasks/bulkdata.py", line 246, in _run_task
    result = self._load_mapping(mapping)
  File "/Users/dglick/Work/CumulusCI/cumulusci/tasks/bulkdata.py", line 253, in _load_mapping
    result = self._wait_for_job(job_id)
  File "/Users/dglick/Work/CumulusCI/cumulusci/tasks/bulkdata.py", line 100, in _wait_for_job
    result = self._job_state_from_batches(job_id)
  File "/Users/dglick/Work/CumulusCI/cumulusci/tasks/bulkdata.py", line 64, in _job_state_from_batches
    uri = urljoin(self.bulk.endpoint + "/", "job/{0}/batch".format(job_id))
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 418, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/Users/dglick/.pyenv/versions/2.7.15/envs/cci-dev-py27/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

**Comment by davisagli** [comment]
Fixed in 2.1.1
