### ISSUE TITLE
Homebrew installation of cci blocked by uritemplate.py

### ISSUE THREAD

**Issue by jstvz** [SFDO-Tooling/CumulusCI#883]
`uritemplate.py` is a pointer to `uritemplate==2.0.0`. After `brew install cumulusci`:

```shell
/usr/local/bin/cci version
```

    Traceback (most recent call last):
      File "/usr/local/bin/cci", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
        @_call_aside
      File "/usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
        f(*args, **kwargs)
      File "/usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
        ws.require(__requires__)
      File "/usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'uritemplate.py==3.0.2' distribution was not found and is required by cumulusci

This means the `uritemplate.py` package is not being installed correctly. Other github issues:

1.  <https://github.com/mapbox/homebrew-cli/issues/1>
2.  <https://github.com/python-hyper/uritemplate/issues/27>
    
    Workaround from #1

```shell
/usr/local/Cellar/cumulusci/2.1.2/libexec/bin/pip install uritemplate.py
```

    Requirement already satisfied: uritemplate.py in /usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages (3.0.2)
    Requirement already satisfied: uritemplate>=2.0 in /usr/local/Cellar/cumulusci/2.1.2/libexec/lib/python3.7/site-packages (from uritemplate.py) (3.0.0)

Should resolve it:

```shell
/usr/local/bin/cci version
```

    Checking the version!
    2.1.2
    
Dependency on `uritemplate.py` should be removed if possible.

**Comment by davisagli** [comment]
Fixed in master
