### ISSUE TITLE
bulkdata query with record_type breaks

### ISSUE THREAD

**Issue by davisagli** [SFDO-Tooling/CumulusCI#904]
Trying to use the QueryData task with a mapping that specifies a record_type breaks like this:

```
[32m2018-12-13 16:16:04:[0m Submitting query: SELECT Id, Name, Phone, Website FROM Account WHERE RecordType.DeveloperName = 'HH_Account'
[32m2018-12-13 16:16:05:[0m Batch id: 7511I00000AzoNRQAZ
[32m2018-12-13 16:16:05:[0m Batch 7511I00000AzoNRQAZ finished
[32m2018-12-13 16:16:05:[0m Job 7501I00000BIcg0QAD closed
[32m2018-12-13 16:16:06:[0m Result id: 7521I000006L049
[32m2018-12-13 16:16:06:[0m Result 7521I000006L049 downloaded
[32m2018-12-13 16:16:06:[0m Done! (Total: 2)
Traceback (most recent call last):
File "c:\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
context)
File "c:\python37\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "households_pkey"
DETAIL: Key (sfhh_id)=() already exists.
```

This is happening because `process_incoming_rows` is not removing the newline character before appending the record_type to the row, so we end up with extra rows with the wrong number of columns.

**Comment by davisagli** [comment]
Fixed in cumulusci 2.2.4
