### ISSUE TITLE
ci_master failing on python 3.7

### ISSUE THREAD

**Issue by mishraankit191** [SFDO-Tooling/CumulusCI#962]
when we run ci_master on our system with python 3.5 it fails at the following sub-flow/task
[32m2019-02-01 11:56:52:[0m ---------------------------------------
[32m2019-02-01 11:56:52:[0m Initializing flow: deploy_packaging
[32m2019-02-01 11:56:52:[0m ---------------------------------------
[32m2019-02-01 11:56:52:[0m
[32m2019-02-01 11:56:52:[0m Flow Description: Process and deploy the package metadata to the packaging org
[32m2019-02-01 11:56:52:[0m Steps:
[32m2019-02-01 11:56:52:[0m   unschedule_apex: Unschedule all scheduled apex jobs (CronTriggers).
[32m2019-02-01 11:56:52:[0m   create_managed_src: Modifies the src directory for managed deployment.  Strips //cumulusci-managed from all Apex code
[32m2019-02-01 11:56:52:[0m   update_package_xml: Updates src/package.xml with metadata in src/
[32m2019-02-01 11:56:52:[0m   deploy: Deploys the src directory of the repository to the org
[32m2019-02-01 11:56:52:[0m   revert_managed_src: Reverts the changes from create_managed_src
[32m2019-02-01 11:56:52:[0m Organization:
[32m2019-02-01 11:56:52:[0m   Username: <username>
[32m2019-02-01 11:56:52:[0m     Org Id: <OrgId>
[32m2019-02-01 11:56:52:[0m Org info updated, writing to keychain
[32m2019-02-01 11:56:52:[0m Options:
[32m2019-02-01 11:56:52:[0m   apex: for (CronTrigger t : [SELECT Id FROM CronTrigger]) { System.abortJob(t.Id); }
[32m2019-02-01 11:56:52:[0m
[32m2019-02-01 11:56:52:[0m Running task: unschedule_apex
[32m2019-02-01 11:56:52:[0m Beginning task: AnonymousApexTask
[32m2019-02-01 11:56:52:[0m
[32m2019-02-01 11:56:52:[0m Executing anonymous Apex
[32m2019-02-01 11:56:53:[0m Anonymous Apex Success
[32m2019-02-01 11:56:53:[0m Task complete: unschedule_apex
[32m2019-02-01 11:56:53:[0m Options:
[32m2019-02-01 11:56:53:[0m   path: src
[32m2019-02-01 11:56:53:[0m   revert_path: src.orig
[32m2019-02-01 11:56:53:[0m
[32m2019-02-01 11:56:53:[0m Running task: create_managed_src
[32m2019-02-01 11:56:53:[0m Beginning task: CreateManagedSrc
[32m2019-02-01 11:56:53:[0m
[32m2019-02-01 11:57:06:[0m Removing the string //cumulusci-managed from src/classes and src/triggers
[32m2019-02-01 11:57:06:[0m [31mTask failed: create_managed_src[0m
[32m2019-02-01 11:57:06:[0m [31mFailing flow due to exception in task[0m
Traceback (most recent call last):
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 296, in _run_task
    task()
  File "c:\cci\lib\site-packages\cumulusci\core\tasks.py", line 137, in __call__
    self.result = self._run_task()
  File "c:\cci\lib\site-packages\cumulusci\tasks\metadata\managed_src.py", line 54, in _run_task
    self.logger,
  File "c:\cci\lib\site-packages\cumulusci\utils.py", line 49, in findReplace
    s = f.read()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2686: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\cci\Scripts\cci.exe\__main__.py", line 9, in <module>
  File "c:\cci\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\cci\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\cci\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cci\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\cci\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\cci\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\cci\lib\site-packages\cumulusci\cli\cci.py", line 213, in new_func
    func(config, *args, **kw)
  File "c:\cci\lib\site-packages\cumulusci\cli\cci.py", line 1161, in flow_run
    handle_exception_debug(config, debug, no_prompt=no_prompt)
  File "c:\cci\lib\site-packages\cumulusci\cli\cci.py", line 1153, in flow_run
    flow()
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 216, in __call__
    self._run_step(stepnum, step_config)
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 243, in _run_step
    self._run_flow(stepnum, step_config)
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 271, in _run_flow
    flow()
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 216, in __call__
    self._run_step(stepnum, step_config)
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 245, in _run_step
    self._run_task(stepnum, step_config)
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 307, in _run_task
    raise e
  File "c:\cci\lib\site-packages\cumulusci\core\flows.py", line 296, in _run_task
    task()
  File "c:\cci\lib\site-packages\cumulusci\core\tasks.py", line 137, in __call__
    self.result = self._run_task()
  File "c:\cci\lib\site-packages\cumulusci\tasks\metadata\managed_src.py", line 54, in _run_task
    self.logger,
  File "c:\cci\lib\site-packages\cumulusci\utils.py", line 49, in findReplace
    s = f.read()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2686: character maps to <undefined>

we're able to run the same without any issues on another system with python 2.7

please advise

**Comment by davisagli** [comment]
@mishraankit191 what version of CumulusCI are you running? (check with `cci version`)

**Comment by mishraankit191** [comment]
@davisagli 2.2.6

**Comment by davisagli** [comment]
@mishraankit191 we released cumulusci 2.3.0 including a change that I'm hoping will fix this.

**Comment by mishraankit191** [comment]
@davisagli It did, I made an update yesterday and was able to run the same flow without any issues, thank you!
